# Creating Tag directories for all reads

# Setting up initial directories structure.
mkdir -p final input log output/tagDirectory/{unique/{control/individualSample/{input/{1,3,5},chip/{2,4,6}},taggedProtein/individualSample/{input/{7,9,11},chip/{8,10,12}}},multimappers/{control/individualSample/{input/{1,3,5},chip/{2,4,6}},taggedProtein/individualSample/{input/{7,9,11},chip/{8,10,12}}}}

# Making symbolic links for input data.

for i in `ls ../../../00-mapping/hisat2/final/*`
do
  ln -s ../${i} input/
done

# Making symbolic link for the fasta of the genome.
ln -s /project/carol/chiporcs/orgn/tryCru-clb/tryCru-clb1/genome/final/tryCru-clb1.fasta input/

# Making a Homer Tag Directory.
# -sspe = paired-end reads.
# -unique = keep only uniquely aligned reads with a MAPQ score greater than 10.
# -keepOne = keep all primary alignments, regardless of MAPQ score. Alignments with the "secondary alignment" flag will be discarded.
# -totalReads <all> = provides the total number of reads (unique+multipappers) in the tag directory.
# -single = place all reads into a single tag file instead of separate files for each chromosome.This is necessary for genome assemblies composed of thousand of scaffolds.

# UNIQUE
# Individual samples.
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlInput1.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/input/1/ input/1.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlInput1.err > log/makeTagDirectoryUniqueIndividualSampleControlInput1.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlInput3.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/input/3/ input/3.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlInput3.err > log/makeTagDirectoryUniqueIndividualSampleControlInput3.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlInput5.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/input/5/ input/5.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlInput5.err > log/makeTagDirectoryUniqueIndividualSampleControlInput5.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput7.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/input/7/ input/7.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput7.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput7.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput9.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/input/9/ input/9.sam format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput9.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput9.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput11.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/input/11/ input/11.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput11.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinInput11.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlChip2.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/chip/2/ input/2.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlChip2.err > log/makeTagDirectoryUniqueIndividualSampleControlChip2.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlChip4.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/chip/4/ input/4.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlChip4.err > log/makeTagDirectoryUniqueIndividualSampleControlChip4.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleControlChip6.time saveCommand makeTagDirectory output/tagDirectory/unique/control/individualSample/chip/6/ input/6.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleControlChip6.err > log/makeTagDirectoryUniqueIndividualSampleControlChip6.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip8.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/chip/8/ input/8.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip8.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip8.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip10.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/chip/10/ input/10.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip10.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip10.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip12.time saveCommand makeTagDirectory output/tagDirectory/unique/taggedProtein/individualSample/chip/12/ input/12.sam -format sam -sspe -unique -mapq 10 -tbp 1 2> log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip12.err > log/makeTagDirectoryUniqueIndividualSampleTaggedProteinChip12.out 

# MULTIMAPPERS
# Individual samples.
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlInput1.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/input/1/ input/1.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlInput1.err > log/makeTagDirectoryMultimappersIndividualSampleControlInput1.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlInput3.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/input/3/ input/3.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlInput3.err > log/makeTagDirectoryMultimappersIndividualSampleControlInput3.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlInput5.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/input/5/ input/5.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlInput5.err > log/makeTagDirectoryMultimappersIndividualSampleControlInput5.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput7.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/input/7/ input/7.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput7.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput7.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput9.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/input/9/ input/9.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput9.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput9.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput11.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/input/11/ input/11.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput11.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinInput11.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlChip2.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/chip/2/ input/2.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlChip2.err > log/makeTagDirectoryMultimappersIndividualSampleControlChip2.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlChip4.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/chip/4/ input/4.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlChip4.err > log/makeTagDirectoryMultimappersIndividualSampleControlChip4.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleControlChip6.time saveCommand makeTagDirectory output/tagDirectory/multimappers/control/individualSample/chip/6/ input/6.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleControlChip6.err > log/makeTagDirectoryMultimappersIndividualSampleControlChip6.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip8.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/chip/8/ input/8.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip8.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip8.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip10.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/chip/10/ input/10.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip10.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip10.out 
/usr/bin/nice -n 19 /usr/bin/time --verbose --output=log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip12.time saveCommand makeTagDirectory output/tagDirectory/multimappers/taggedProtein/individualSample/chip/12/ input/12.sam -format sam -sspe -keepAll -mapq 10 -tbp 1 2> log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip12.err > log/makeTagDirectoryMultimappersIndividualSampleTaggedProteinChip12.out 


